const ERROR_CODE = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_SERVER = 500;
const SUCCESS = 200;
const CREATED = 201;
const BASE_ERROR = 11000;
const CONFLICT_REQUEST = 409;

module.exports = {
  ERROR_CODE,
  ERROR_NOT_FOUND,
  ERROR_SERVER,
  SUCCESS,
  BASE_ERROR,
  CONFLICT_REQUEST,
  CREATED,
};
